apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-qa
resources:
- ../../../base/fe

patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress

images:
- name: scgskku/shortener-fe
  newName: scgskku/shortener-fe-qa
- name: scgskku/shortener-fe-qa
  newTag: 8799fb802ce4104069ab168d6ec477c489a3d093
