apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-qa
resources:
- namespace.yaml
- secret.yaml
- ../../../base/fe

patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress

images:
- name: scgskku/shortener-fe-qa
  newTag: 0.0.1
