apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shortener-api-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-clusterissuer'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - shortener.scg.skku.ac.kr
      secretName: gitops-tls
  rules:
    - host: shortener.scg.skku.ac.kr
      http:
        paths:
          - path: /short(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: shortener-api-service
                port:
                  number: 80
