apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shortener-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-clusterissuer"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - shortener.scg.skku.ac.kr
      secretName: gitops-be-tls
  rules:
    - host: shortener.scg.skku.ac.kr
      http:
        paths:
          - path: /v1/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: shortener-api-service
                port:
                  number: 80
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: shortener-api-service
                port:
                  number: 80