apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-qa
resources:
- namespace.yaml
- secret.yaml
- ../../../base/api

patches:
- path: domain.json
  target:
    kind: Ingress
    name: shortener-api-ingress

images:
- name: scgskku/shortener-api
  newName: scgskku/shortener-api-qa
- name: scgskku/shortener-api-qa
  newTag: 253c2bd998ca8fa45d5e1a9f492720928d03a7bb
