apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-prod
resources:
- ../../../base/fe

patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress

images:
- name: scgskku/shortener-fe
  newName: scgskku/shortener-fe-prod
- name: scgskku/shortener-fe-prod
  newTag: 4a4aa8845e08d0f56fde66f2dd22a08224f229f5
