apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-prod
resources:
  - namespace.yaml
  - secret.yaml
  - ../../../base/api

patches:
  - path: domain.json
    target:
      kind: Ingress
      name: shortener-api-ingress

images:
  - name: scgskku/shortener-api
    newName: scgskku/shortener-api
    newTag: 0.0.1
