apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-prod
resources:
- namespace.yaml
- secret.yaml
- ../../../base/api

patches:
- path: domain.json
  target:
    kind: Ingress
    name: shortener-api-ingress

images:
- name: scgskku/shortener-api-prod
  newTag: bce8ea35c57723fd0d91737495e2b1a4fa6815fd
