apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortener-prod
resources:
- namespace.yaml
- secret.yaml
- ../../../base/api

patches:
- path: domain.json
  target:
    kind: Ingress
    name: shortener-api-ingress

images:
- name: scgskku/shortener-api
  newName: scgskku/shortener-api-prod
- name: scgskku/shortener-api-prod
  newTag: 831c60ee88e7a03d419d0d056ae65aea817cf05d
